### ISSUE TITLE
PFCP_IE_CREATE_BAR not handled

### ISSUE THREAD

**Issue by yoursunny** [OPENAIRINTERFACE/openair-spgwu-tiny#85]
I'm testing **oai-spgwu-tiny** with an SMF implementation from Open5GCore (commercial product).
I got the OAI UPF register with these environment variables:

```yaml
    environment:
      DNN_0: 'net6'
      ENABLE_5G_FEATURES: 'yes'
      NETWORK_UE_IP: '192.168.0.0/16'
      NRF_IPV4_ADDRESS: '255.255.255.255'
      NSSAI_SD_0: '0xFFFFFF'
      NSSAI_SST_0: '1'
      PGW_INTERFACE_NAME_FOR_SGI: 'eth3'
      REGISTER_NRF: 'no'
      SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP: 'eth1'
      SGW_INTERFACE_NAME_FOR_SX: 'eth2'
      TZ: 'Etc/UTC'
      UPF_FQDN_5G: ''
```

The UPF registers with SMF successfully, but PDU session establishment does not work.
[packet sample on N4 interface](https://github.com/OPENAIRINTERFACE/openair-spgwu-tiny/files/12234266/20230801.zip)

The error message is:

```text
[2023-08-01 21:33:14.494] [pfcp] [error] Unknown PFCP IE type 85 (length 5)
[2023-08-01 21:33:14.494] [spgwu_sx] [info] handle_receive exception PFCP msg 50 Bad Length hdr.length 249/ sum ie 223 / check sum ie 237 Exception /openair-spgwu-tiny/src/pfcp/3gpp_29.244.hpp:528
```

IE type 85 refers to `PFCP_IE_CREATE_BAR`.
I searched the code and it appears that the relevant decoding section is commented out:
https://github.com/OPENAIRINTERFACE/openair-spgwu-tiny/blob/93df89971f8bce5595489d8a8a02a4c1fd6a17b2/src/pfcp/3gpp_29.244.cpp#L510-L515

Is there any particular reason for this?
